spring:
  ai:
    model:
      chat: openai
    openai:
      api-key: ${OPEN_API_KEY}
      chat:
        options:
          model: gpt-5-mini
          temperature: 1
      embedding:
        options:
          model: text-embedding-3-small
    prompt:
      system-path: classpath:prompts/system-prompt.txt
      empty-context-path: classpath:prompts/empty-context-prompt.txt
    rag:
      min-docs: 2
      min-total-chars: 100
      min-score: 0
      retriever:
        top-k: 6
        similarity-threshold: 0.5

qdrant:
  api-key: ${QDRANT_API_KEY}
  host: ${QDRANT_HOST}
  port: ${QDRANT_PORT}
