spring:
  profiles:
    active: dev # 로컬에서 실행할 때의 기본값
    group:
      dev:
        - "oauth"
        - "llm"
      prod:
        - "oauth"
        - "llm"

  # 공통 애플리케이션 설정
  application:
    name: simvex

  # JPA/Hibernate 공통 설정
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# 로깅 공통 설정
logging:
  level:
    root: info
    com.simvex: debug

# swagger
springdoc:
  default-consume-media-type: application/json
  default-produce-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs