spring:
  ai:
    model:
      chat: openai
    openai:
      api-key: ${OPEN_API_KEY}
      chat:
        options:
          model: gpt-5-mini
          temperature: 1
      embedding:
        options:
          model: text-embedding-3-small
    prompt:
      system-path: classpath:prompts/system-prompt.txt

qdrant:
  api-key: ${QDRANT_API_KEY}
  host: ${QDRANT_HOST}
  port: ${QDRANT_PORT}

ai:
